# syntax=docker/dockerfile:1
FROM python:3.11
RUN apt update
RUN apt install -y python3-dev build-essential ffmpeg
RUN rm -r /var/lib/apt/lists/*
RUN pip install --upgrade pip
WORKDIR /code
COPY requirements.rss.txt requirements.rss.txt
RUN pip install -r requirements.rss.txt
COPY rss ./rss
COPY logs ./logs
COPY run_rss.py config.py logging.yaml ./
