# syntax=docker/dockerfile:1
FROM python:3.11
RUN apt update
RUN apt install -y python3-dev build-essential
RUN rm -r /var/lib/apt/lists/*
RUN pip install --upgrade pip
WORKDIR /code
COPY requirements.bot.txt requirements.bot.txt
RUN pip install -r requirements.bot.txt
COPY bot ./bot
COPY assets ./assets
COPY logs ./logs
COPY run_bot.py config.py logging.yaml ./
